### ISSUE TITLE
SP's cannot create profiles 

### ISSUE THREAD

**Issue by seamustuohy** [ASL-19/civicdr-backend#1]
There seems to have been a regression in the latest code update. SP's can no longer create profiles. The server response is as follows.

```json
{"statusCode":422,
"error":"Unprocessable Entity",
"message":"Record is missing required field rating"}
```

**Comment by MayaAvaz** [comment]
On a related note, even when admin creates the profile for SP, SP is asked to create a profile when logs in for the first time which they cannot do as Seamus explained. SP still can got the dashboard page but is not able to see the tickets assigned to them. 

Do we have any ETA for the fix for this bug?

**Comment by majorzazz** [comment]
@MayaAvaz, can you clarify that these are the steps you're taking? It sounds like you've been hit by a separate bug if the flow is:

1. Create user in Auth0
2. Logged in as Admin, create an SP with the Open ID from Auth0
3. Log out from Admin
4. Log in as that SP

_Then_ you're not taken straight to the main page (ie, ticket list), but instead taken to edit the SP's profile (ie, your own profile)? The proper flow would be to go straight to the main page.

(FWIW, I'm not able to replicate this particular erroneous flow.)

**Comment by MayaAvaz** [comment]
@majorzazz Yes, I took the steps you mentioned. I tried it now one more time with the same result. I took the Open ID from user's Raw Jason (is that correct?)

**Comment by majorzazz** [comment]
@MayaAvaz, hmm, yeah, you should be taking `user_id` from that user's Raw JSON, form of something like `auth0|${bunch of letters and numbers}`.

**Comment by seamustuohy** [comment]
In the latest build [a4dbd6faa6efd9c3a2df39d707c6f334169d49da](https://github.com/ASL-19/civicdr-backend/commit/a4dbd6faa6efd9c3a2df39d707c6f334169d49da) SP's can now create profiles.
