### ISSUE TITLE
Improve time formatting in email notifications (or remove entirely)

### ISSUE THREAD

**Issue by GrantASL19** [ASL-19/civicdr-backend#19]
At the moment the time format in email notifications isn’t user-friendly:

> Update on the platform at 2017-07-21T19:37:03+00:00. Log in to review.

It should be something like:

> Update on the platform at 19:37 UTC. Log in to review.

Alternatively, if the emails are sent in real-time, it might make more sense to remove the date/time since it’s redundant. This way we won’t have to worry about time zone and regional date format confusion.

**Comment by seamustuohy** [comment]
The e-mails are sent in batches. We can set those batches to run once every 10 minutes, every hour, or every day.

**Comment by seamustuohy** [comment]
Addressing this issue in the following branch. https://github.com/ASL-19/civicdr-backend/tree/issue_18_21

**Comment by seamustuohy** [comment]
Closed by [pull request #24](https://github.com/ASL-19/civicdr-backend/pull/24)

Here is an example of the new date formats. ```Jul 25 15:53 UTC```
