### ISSUE TITLE
Threads Updates by IP or SP don't generate email to admin

### ISSUE THREAD

**Issue by MayaAvaz** [ASL-19/civicdr-backend#21]
Threads Updates by IP or SP don't generate email to admin.

**Comment by seamustuohy** [comment]
Addressing this issue in the following branch. https://github.com/ASL-19/civicdr-backend/tree/issue_18_21

**Comment by seamustuohy** [comment]
Closed by [pull request #24](https://github.com/ASL-19/civicdr-backend/pull/24)
