### ISSUE TITLE
Email should be sent to admin in case of updates in ticket by IP or SP

### ISSUE THREAD

**Issue by MayaAvaz** [ASL-19/civicdr-backend#26]
Logged in as an IP. Edited an existing a ticket. No email was generated for admin (checked the database). 
Did the same thing as SP and no email was generated on that case either.

**Comment by seamustuohy** [comment]
Tickets currently only update IP's and SP's when there is a status update. Should we have every edit to the tickets notify the other parties involved?

**Comment by MayaAvaz** [comment]
I think the updates by SP and IP might have something we would like to know. Hard to say without seeing real world scenarios though, I agree.
